name: Discord Notification

on:
  push:
    branches:
      - main
      - discord-entegration2

jobs:
  discord:
    runs-on: ubuntu-latest
    needs: [deploy]  # garante que sรณ roda depois do deploy
    steps:
      - uses: actions/checkout@v4

      - name: Send Discord Notification
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
